version: '3'
services:
  app:
    container_name: technqn-api
    restart: always
    build: .
    ports:
      - '80:5000'
    links:
      - mongo-db
  mongo-db:
    container_name: mongo-db
    image: mongo
    ports:
      - '27017:27017'