version: '3'
services:
  app:
    container_name: technqn-api
    restart: always
    build: .
    ports:
      - '80:5000'
    links:
      - technqn-mongo
  mongo:
    container_name: technqn-mongo
    image: mongo
    ports:
      - '27017:27017'