version: '3'
services:
  app:
    container_name: hasel-api
    restart: always
    build: .
    ports:
      - '81:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'